version: "3"
services:
  directus:
    image: directus/directus
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      # DB_CLIENT: "pg"
      # DB_HOST: "database"
      # DB_PORT: "5432"
      # DB_DATABASE: "directus"
      # DB_USER: "directus"
      # DB_PASSWORD: "directus"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: ${ADMIN_PASS}
